config/routes.rb
Rails.application.routes.draw do

  get 'top' => 'top#index'
  get 'top/intro' => 'top#intro'

  get 'recipes/index' => 'recipes#index'
  get 'books/index' => 'books#index'

  get 'create/index' => 'create#index'
  post 'create/post' => 'create#post'

  get 'signup' => 'users#new'
  post 'signup' => 'users#signup'
  
  get 'signin' => 'users#signin_form'
  post 'signin' => 'users#signin'

  post 'signout' => 'users#signout'

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :reports
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, {uniqueness: true}
  validates :email, {presence: true}
  validates :name, {uniqueness: true}
  validates :name, {presence: true}
  validates :password_digest, {presence: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:keyword]
      @books = RakutenWebService::Books::Book.search(title: params[:keyword])
    end
  end
end

app/controllers/create_controller.rb
class CreateController < ApplicationController
  def index
    @recipe = Recipe.find(params[:recipe_id])
  end

  def post
    # t.string "age"
    # t.string "sex"
    # t.string "user_id"
    # t.string "recipe_id"
    # t.datetime "created_at", null: false
    # t.datetime "updated_at", null: false

    Report.create(sex: params[:sex],
                  age: params[:age],
                  user_id: params[:user_id],
                  recipe_id: params[:recipe_id],
                  comment: params[:comment]
                  )
    redirect_to top_path
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    if params[:zairyou]
      @recipes = Recipe.where("material LIKE ?", "%#{params[:zairyou]}%")
      if params[:jikan]
        @recipes = @recipes.where("indication LIKE ?", "%#{params[:jikan]}%")
      end
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @reports = Report.all.order(created_at: :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def signup
    @user = User.new(name: params[:name], email: params[:email], password: params[:password])
    if @user.save
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to recipes_index_path
    else
      render("users/new")
    end
  end

  def signin_form
  end
  
  def signin
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to recipes_index_path
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render("users/signin_form")
    end
  end

  def signout
    session[:user_id] = nil
    flash[:notice] = 'ログアウトしました'
    redirect_to recipes_index_path
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/create_helper.rb
module CreateHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_result.html.erb
<table border="1" class="dataframe table table-bordered table-hover">
  <thead>
    <tr style="text-align: right;">
      <th>title</th>
      <th>auther</th>
      <th>caption</th>
      <th>image</th>
    </tr>
  </thead>
  <% @books.each do |book| %>
    <tbody>
      <tr>
        <td> <%= book.title %> </td>
        <td> <%= book.author %> </td>
        <td> <%= book.item_caption %> </td>
        <td> <%= link_to (image_tag(book.medium_image_url)), book.item_url %> </td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

<div class="search-box">
  <%= form_with url: books_index_path, method: :get, local: true do |form| %>
  <!--フォーム内容 -->
    <div class="form-group">
      <%= form.text_field :keyword, class: "form-control"%>
      <%= form.submit '本の題名を検索', class: "form-control btn btn-success"%>
    </div>
  <% end %>
</div>

<div>
  <% if @books.present? %>
    <%= render partial: 'result'%>
  <% end %>
</div>

app/views/create/index.html.erb
<p>作ってくれてありがとう</p>

<div>
  <table border="1" class="dataframe table table-bordered table-hover">
    <thead>
      <tr style="text-align: right;">
        <th>recipeTitle</th>
        <th>recipeIndication</th>
        <th>recipeCost</th>
        <th>recipeMaterial</th>
        <th>image</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= @recipe.title %> </td>
        <td> <%= @recipe.indication %> </td>
        <td> <%= @recipe.cost %> </td>
        <td> <%= @recipe.material.delete('"[]') %> </td>
        <td> <%= image_tag @recipe.food_image_url, :style => "height: 120px" %>
      </tr>
    </tbody>
  </table>
</div>

<div class="accept-box">
  <%= form_with url: create_post_path, method: :post, local: true do |f| %>
    <div class="form-group">
      <% if session[:user_id] %>
        <%= f.hidden_field :user_id, :value => session[:user_id] %> 
      <% end %>
      <%= f.hidden_field :recipe_id, :value=> @recipe.id %>
      <%= f.label :sex, '性別' %>
      <%= f.select :sex, {'男性': '男性', '女性': '女性'},
                          { include_blank: '選択してください'},
                          { class: 'form-control' , required: true } %>
      <%= f.label :age, '年齢' %>
      <%= f.select :age, {'20代未満': '20代未満', '20代': '20代', '30代': '30代',
                          '40代': '40代', '50代': '50代', '60代以上': '60代以上'},
                          { include_blank: '選択してください'},
                          { class: 'form-control' , required: true } %>

      <%= f.label :comment, 'コメント' %>
      <%= f.text_area :comment %>      
      <%= f.submit '投稿する', class: "form-control btn btn-success"%>
    </div>
  <% end %>
  <%= link_to "投稿しません", top_path %>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saladays</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <header>
    <div>
      <h1><%= link_to "Saladays", top_path %></h1>
      <li>
        <%= link_to "つくる", recipes_index_path %>
      </li>
      <li>
      <%= link_to "うp主", top_intro_path %>
      </li>
      <% if session[:user_id] %>
        <li>
          現在のユーザーid : <%= session[:user_id] %>
        </li>
        <li>
          <%= link_to "sign Out", signout_path, data: {turbo_method: :post}  %>
        </li>
      <% else %>
        <li>
          <%= link_to "sign Up", signup_path %>
        </li>
        <li>
          <%= link_to "sign In", signin_path %>
        </li>
      <% end %>
    </div>
  </header>
  
  <% if flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>
  
  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>

  <footer>
    <div class="profile">
      <h1>フッター</h1>
    </div>
  </footer>
</html>

app/views/recipes/_result.html.erb
<table border="1" class="dataframe table table-bordered table-hover">
  <thead>
    <tr style="text-align: right;">
      <th>recipeTitle</th>
      <th>recipeIndication</th>
      <th>recipeCost</th>
      <th>recipeMaterial</th>
      <th>image</th>
    </tr>
  </thead>
  <% @recipes.each do |recipe| %>
  <tbody>
    <tr>
      <td> <%= recipe.title %> </td>
      <td> <%= recipe.indication %> </td>
      <td> <%= recipe.cost %> </td>
      <td> <%= recipe.material.delete('"[]') %> </td>
      <td> <%= image_tag recipe.food_image_url, :style => "height: 120px" %>
      <br>
      <br>
      <%= link_to "つくる", create_index_path(recipe_id: recipe.id), onclick: "window.open('#{recipe.url}', '_blank')" %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/recipes/index.html.erb
<div class="search-box">
  <%= form_with url: recipes_index_path, method: :get, local: true do |f| %>
    <div class="form-group">      
      <%= f.radio_button :jikan , ''%>
      <%= f.label :jikan ,"なんでもいいです", value: '' %>
      <br>
      <%= f.radio_button :jikan ,'5分以内' %>
      <%= f.label :jikan ,"サラダなる食べ物があるそうで", value: '5分以内', style: "display: inline-block;" %>
      <br>
      <%= f.radio_button :jikan ,'約10分' %>
      <%= f.label :jikan ,"皿は用意してあります", value: '約10分', style: "display: inline-block;" %>
      <br>
      <%= f.radio_button :jikan ,'約15分' %>
      <%= f.label :jikan ,"野菜が恋しいかも", value: '約15分', style: "display: inline-block;"%>
      <br>
      <%= f.radio_button :jikan ,'約30分' %>
      <%= f.label :jikan ,"これがサラダモチベーションか", value: '約30分', style: "display: inline-block;" %>
      <br>
      <%= f.radio_button :jikan ,'約1時間' %>
      <%= f.label :jikan ,"サラダのための1時間は1分", value: '約1時間', style: "display: inline-block;" %>
      <br>
      <%= f.radio_button :jikan ,'1時間以上' %>
      <%= f.label :jikan ,"サラダになりたいなーぁぁぁ！！", value: '1時間以上', style: "display: inline-block;" %>
      <br>
      <p>材料で検索</p>
      <%= f.text_field :zairyou, class: "form-control"%>
      <%= f.submit 'サラダのレシピを検索', class: "form-control btn btn-success"%>
    </div>
  <% end %>
</div>

<div>
  <% if @recipes.present? %>
    <%= render partial: 'result'%>
  <% else %>
    <p>検索条件を変えてみてね</p>
  <% end %>
</div>

app/views/top/index.html.erb
<div class="hero">
  <%= link_to "サラダをつくる", recipes_index_path %>
</div>
<br>
<div>
  <h1>みんなのサラダ</h1>
  <table border="1" class="dataframe table table-bordered table-hover">
    <thead>
      <tr style="text-align: right;">
        <th>性別</th>
        <th>年齢</th>
        <th>recipe_id</th>
        <th>user_id</th>
        <th>recipe_title</th>
        <th>comment</th>
        <th>image</th>
      </tr>
    </thead>
    <% @reports.each do |report| %>
      <% recipe = Recipe.find(report.recipe_id) %>
      <tbody>
        <tr>
          <td> <%= report.sex %> </td>
          <td> <%= report.age %> </td>
          <td> <%= report.recipe_id %> </td>
          <td> <%= report.user_id %> </td>
          <td> <%= recipe.title %> </td>
          <td> <%= report.comment %> </td>
          <td> <%= image_tag recipe.food_image_url, :style => "height: 120px" %> 
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<div class="form-heading">新規ユーザー登録</div>
  <div class="form users-form">
    <div class="form-body">

      <% @user.errors.full_messages.each do |message| %>
      <div class="form-error">
        <%= message %>
      </div>
      <% end %>

      <%= form_with url: signup_path, method: :post, local: true do |f| %>
        <p>ユーザー名</p>
        <%= f.text_field :name, class: ""%>
        <p>メールアドレス</p>
        <%= f.text_field :email, class: ""%>
        <p>パスワード</p>
        <%= f.password_field :password %>
        <%= f.submit '新規登録', class: "form-control btn btn-success"%>
      <% end %>
    </div>
  </div>
</div>

app/views/users/signin_form.html.erb
<div class="form-heading">ログイン</div>
<div class="form users-form">
  <div class="form-body">
    <% if @error_message %>
      <div class="form-error">
        <%= @error_message %>
      </div>
    <% end %>
    <%= form_with(url: signin_path, local: true) do |f| %>
      <p>メールアドレス</p>
      <%= f.email_field :email ,placeholder: @email %>
      <p>パスワード</p>
      <%= f.password_field :password ,value: @password %>
      <%= f.submit 'SignIn', class: "form-control btn btn-success"%>
    <% end %>
  </div>
</div>